# -*- coding: utf-8 -*-
"""5-quantos-espaco-tem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/110p7S0DzoR0zplhUEBscka-WiT8YEENs
"""

# Crie um programa que receba como input uma string. Em seguida percorra a string e diga quantos espaços em branco essa string tem.

indice = 0
espaco = 0
texto = str(input("Digite um texto: "))

while (indice < len(texto)):
  char = texto[indice]
  print(char)
  if (char == " "):
    espaco += 1
  indice += 1
print("A quantidade de espaço em branco neste texto é: ", (espaco))