# -*- coding: utf-8 -*-
"""1atividade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n5gzv-lE4El8Gy_48i5JKOkx3cm1oleI
"""

# Crie um programa que receba 5 numeros e retorne a média artimetica entre esse numeros

soma = 0
cont = 0

while (cont < 5):
  num = float(input("Digite um valor: "))
  soma += num
  cont += 1
  res = soma / 5
print("A média dos 5 numeros é: ", res)