# -*- coding: utf-8 -*-
"""soma-5numeros-positivos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i-e7laeB3smMh48sHuD8Ib5rjpBjij7z
"""

# Crie um programa que receba 5 números, realiza a soma destes números, mas caso um destes números seja negativo não considere ele na soma

soma = 0
cont = 0

while (cont < 5 ):
  num = float(input("Digite um valor: "))
  if (num < 0):
    continue
  soma += num
  cont += 1
print("O valor da soma é: ", soma)