# -*- coding: utf-8 -*-
"""3-recebe-quantidade-de-numeros-ler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/110p7S0DzoR0zplhUEBscka-WiT8YEENs
"""

# Crie um programa que receba um número arbitrario de numeros que serão lidos e retorne a soma de todos eles

soma = 0
cont = 0

rep = int(input("Digite a quantidade de numeros que desejar ler: "))

while (cont < rep):
  num = float(input("Digite um valor: "))
  soma += num
  cont += 1
print("O valor da soma dos %i números é: %d " % (rep, soma))