# -*- coding: utf-8 -*-
"""4-par-ou-impar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/110p7S0DzoR0zplhUEBscka-WiT8YEENs
"""

# Percorra os números de 2 até 10 e diga se o número é par ou impar

indice = 2
while (indice <= 10):
  resto = (indice % 2)
  if resto == 0:
    print("O número %d é par " % (indice))
  else:
    print("O número %d é impar " %(indice))
  indice += 1

print("Encerrou")